### ISSUE TITLE
Login flow is sometimes broken

### ISSUE THREAD

**Issue by eminence** [BENDERFACToRY/vault#16]
A few people have reported being unable to login.  Looking at the logs, I see these messages:

```
Searching user: {
  id: 'aaaa',
  // rest of the object elided
}
creating user: {
  id: 'aaaa',
  // rest of the object elided
}
Error: Uniqueness violation. duplicate key value violates unique constraint "discord_pkey"
    at new ApolloError (/app/node_modules/@apollo/client/errors/errors.cjs.js:35:28)
    at /app/node_modules/@apollo/client/core/core.cjs.js:1027:47
    at both (/app/node_modules/@apollo/client/utilities/utilities.cjs.js:1004:53)
    at /app/node_modules/@apollo/client/utilities/utilities.cjs.js:997:72
    at new Promise (<anonymous>)
    at Object.then (/app/node_modules/@apollo/client/utilities/utilities.cjs.js:997:24)
    at Object.next (/app/node_modules/@apollo/client/utilities/utilities.cjs.js:1005:49)
    at notifySubscription (/app/node_modules/zen-observable/lib/Observable.js:135:18)
    at onNotify (/app/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.next (/app/node_modules/zen-observable/lib/Observable.js:235:7)
```

The uniqueness violation seems legit.  The search apparently is returning no results, even though the user already exists (confirmed by running the query in the hasura console)

Deleting the user from the hasura console and asking them to login again generally fixes the problem.

**Comment by eminence** [comment]
I'm wondering if this is a hasura permission problem

**Comment by dxlbnl** [comment]
Ah, this is due to a database constraint, there is a way of making the insert/update fix the db state. Or we might need to add a check before writing to the db. 

Have to brush up on how this works again, but probably adding a on_conflict will fix the issue. 

https://hasura.io/docs/latest/graphql/core/api-reference/graphql-api/mutation.html#on-conflict-argument

**Comment by dxlbnl** [comment]
Fixed it
